# Generated by Django 4.1.4 on 2022-12-28 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORIES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MODULES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UTILISATEURS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default=False, max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='WILAYAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='MESSAGES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=20)),
                ('contenu', models.TextField()),
                ('rel_utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='ANNONCES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20, null=True)),
                ('contenu', models.TextField()),
                ('tarif', models.IntegerField()),
                ('rel_categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categories')),
                ('rel_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.modules')),
                ('rel_utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.utilisateurs')),
                ('rel_wilaya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wilayas')),
            ],
        ),
    ]
