version: '3'

services:
  backend:
    build: 
      context: ./back-end
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/frontend/app/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8000
    volumes:
      - ./nginx/nginx-setup.conf:/etc/niginx/conf.d/default.conf:ro
      - react_build:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  react_build:           

